# flake8: noqa

"""
    Academic Observatory API

    The REST API for accessing data from academic-observatory-workflows.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from academic_observatory_api.client.api_client import ApiClient

# import Configuration
from academic_observatory_api.client.configuration import Configuration

# import exceptions
from academic_observatory_api.client.exceptions import OpenApiException
from academic_observatory_api.client.exceptions import ApiAttributeError
from academic_observatory_api.client.exceptions import ApiTypeError
from academic_observatory_api.client.exceptions import ApiValueError
from academic_observatory_api.client.exceptions import ApiKeyError
from academic_observatory_api.client.exceptions import ApiException
