"""
    Academic Observatory API

    The REST API for accessing data from academic-observatory-workflows.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


import unittest

import academic_observatory_api.client
from academic_observatory_api.client.api.academic_observatory_api import AcademicObservatoryApi  # noqa: E501


class TestAcademicObservatoryApi(unittest.TestCase):
    """AcademicObservatoryApi unit test stubs"""

    def setUp(self):
        self.api = AcademicObservatoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pit_id_agg(self):
        """Test case for pit_id_agg

        """
        pass

    def test_pit_id_subagg(self):
        """Test case for pit_id_subagg

        """
        pass

    def test_query_agg(self):
        """Test case for query_agg

        """
        pass

    def test_query_subagg(self):
        """Test case for query_subagg

        """
        pass


if __name__ == '__main__':
    unittest.main()
