#This Github action builds docker API images that are uploaded to the GCR and runs a Terraform workflow.
#
#For a pull request event:
#- Run Terraform:
#  - fmt
#  - validate
#  - plan (output is pushed to comment in PR)
#
#For a push event to develop or main:
#- Build and push images
#- Run Terraform:
#  - fmt
#  - validate
#  - plan
#  - apply
#
#For a published release event:
#- Build and push images
#- Run Terraform:
#  - fmt
#  - validate
#  - plan
#
#Develop (target) branch settings:
#- GCP project id: develop, TF workspace: develop, Image tag: develop
#
#Main (target) branch settings:
#- GCP project id: staging, TF workspace: staging, Image tag: staging
#
#Published release settings:
#- GCP project id: production, TF workspace: production, Image tag: <release_name>

name: "API Workflow"

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  release:
    types:
      - published
env:
  # Artifact registry settings for image build
  REGISTRY: us-docker.pkg.dev
  USER_NAME: _json_key_base64
  IMAGE_PATH: observatory-platform/academic-observatory-api

#  # The name of the api (should be same as in the config file)
#  SERVICE: ao

  # The Terraform token and organisation
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_BACKEND_ORGANIZATION: ${{ secrets.TF_BACKEND_ORGANIZATION }}
  TF_GCP_PROJECT_ID: ${{ secrets.TF_GCP_PROJECT_ID }}

  # The Terraform Cloud workspaces for different environments
  DEVELOP_TF_WORKSPACE: ao-develop
  STAGING_TF_WORKSPACE: ao-staging
  PRODUCTION_TF_WORKSPACE: ao-production

  # The GCP keys for different environments
#  DEVELOP_GCP_SERVICE_KEY: ${{ secrets.DEVELOP_GCP_SERVICE_KEY }}
#  STAGING_GCP_SERVICE_KEY: ${{ secrets.STAGING_GCP_SERVICE_KEY }}
#  PRODUCTION_GCP_SERVICE_KEY: ${{ secrets.PRODUCTION_GCP_SERVICE_KEY }}

  # The GCP project ids for different environments
#  DEVELOP_GCP_PROJECT_ID: ${{ secrets.DEVELOP_GCP_PROJECT_ID }}
#  STAGING_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
#  PRODUCTION_GCP_PROJECT_ID: ${{ secrets.PRODUCTION_GCP_PROJECT_ID }}

jobs:
  build-and-push-image:
    name: "Build and push docker image for API"
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
#        environment: [ develop, staging, production ]
        environment: [ develop ]
        include:
          - environment: develop
            gcp_project_id: DEVELOP_GCP_PROJECT_ID
#          - environment: staging
#            gcp_project_id: STAGING_GCP_PROJECT_ID
#          - environment: production
#            gcp_project_id: PRODUCTION_GCP_PROJECT_ID

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.ARTIFACT_REGISTRY_GCP_SERVICE_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ secrets[matrix.gcp_project_id] }}/${{ env.IMAGE_PATH }}
          tags: |
            # On any kind of push, set branch name as image tag
            type=ref,event=branch

            # On push to main branch, set 'latest' as image tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

            # On push of Github tag, set version as image tag
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  terraform:
    needs: build-and-push-image
    if: always()
    name: "Terraform"
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add mask
        run: |
          echo "::add-mask::${{ env.TF_GCP_PROJECT_ID }}" 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ..
          pip install -e .
          
          git clone -b setup https://github.com/The-Academic-Observatory/coki-api-base.git
          pip install -e coki-api-base

      - name: Render openapi file
        run: |
          coki-api-base generate-openapi-spec ../academic_observatory_api/openapi.yaml.jinja2 ./openapi.yaml.tpl --usage-type cloud_endpoints

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Set Terraform Workspace env for push & release event
        if: github.event_name == 'push' || github.event_name == 'release'
        run: |
          if [ ${{ github.event_name }} == 'push' ] ; then
            if [ ${{ github.ref }} == 'refs/heads/main' ] ; then
              echo "TF_WORKSPACE=${{ env.STAGING_TF_WORKSPACE }}" >> $GITHUB_ENV;
            else
              echo "TF_WORKSPACE=${{ env.DEVELOP_TF_WORKSPACE }}" >> $GITHUB_ENV;
            fi
          elif [ ${{ github.event_name }} == 'release' ]; then
            echo "TF_WORKSPACE=${{ env.PRODUCTION_TF_WORKSPACE }}" >> $GITHUB_ENV;
          fi

      - name: Set Terraform Workspace env for pull_request event
        if: github.event_name == 'pull_request'
        run: |
          if [ ${{ github.event.pull_request.base.ref }} == 'develop' ] ; then
            echo "TF_WORKSPACE=${{ env.DEVELOP_TF_WORKSPACE }}" >> $GITHUB_ENV;
          else
            echo "TF_WORKSPACE=${{ env.STAGING_TF_WORKSPACE }}" >> $GITHUB_ENV;
          fi

      - name: Terraform Format
        id: fmt
        run: terraform fmt -diff -check

      - name: Terraform Init
        id: init
        run: terraform init
          -backend-config="organization="${{ env.TF_BACKEND_ORGANIZATION }}""

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Terraform Workflow

      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Workflow
            #### Terraform Format and Style 🖌`${{ steps.fmt.outcome }}`
            #### Terraform Initialization ⚙️`${{ steps.init.outcome }}`
            #### Terraform Validation 🤖`${{ steps.validate.outcome }}`
            #### Terraform Plan 📖`${{ steps.plan.outcome }}`
            <details><summary>Show Plan</summary>

            ```terraform
            ${{ steps.plan.outputs.stdout }}
            ```
            </details>

            *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*
          edit-mode: replace

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
